#pragma once

// ============================================================================
//  EditorApp.h - the editor's shell: the list of panels, the menu bar, and the
//  frame loop.
//
//  ADDING A PANEL IS ONE LINE:
//      AddPanel(std::make_unique<MyPanel>());
//
//  It then appears in the View menu automatically, because that menu is
//  generated by looping over the panel list rather than written out by hand.
//
//  ==========================================================================
//  THE SELECTION LIVES HERE, not in the Hierarchy panel, because two panels
//  share it: the Hierarchy selects, and the Inspector displays. A panel
//  reaching into another panel is worse than both reaching into the shell they
//  belong to.
//
//  IT IS AN EntityId, NEVER AN Entity*. A remembered pointer crashes the first
//  time the selected entity is destroyed; an id is checked and comes back
//  empty. See EntityId.h.
// ============================================================================

#include <engine/Engine.h>

#include <memory>
#include <string>
#include <vector>

#include "panels/Panel.h"

namespace editor {

// State that more than one panel needs. Panels reach it through Get() rather
// than having it passed to them, which is a deliberate simplification: this is
// a tool with exactly one instance of everything, and threading a context
// pointer through every panel would be ceremony with no payoff.
struct EditorState {
    eng::EntityId selected{};
    bool          showImGuiDemo = false;

    // Set by any panel that changes the scene, cleared when it is saved.
    // Purely a prompt for the user - nothing is blocked on it, because a tool
    // that refuses to close is worse than one that loses an edit.
    bool dirty = false;

    // Raised by the Toolbar when Play is pressed, and acted on by EditorApp,
    // which is the only thing that holds the Game panel. A flag rather than a
    // direct call, so no panel needs a pointer to another panel.
    bool focusGameView = false;

    // A scene that the Assets panel or the Scene view asked to open, applied
    // by EditorApp AFTER every panel has finished drawing.
    //
    // DEFERRED, and it has to be. Loading a scene destroys every entity in the
    // current one, and doing that from inside a panel's Draw would pull the
    // ground out from under the panels that have already drawn this frame and
    // are still holding on to what they were describing. It is the same
    // argument DeferredOps makes for the engine, arriving at the editor - and
    // the editor does not get an exemption from the engine's own rules.
    std::string requestedScene;

    static EditorState& Get();
};

class EditorApp {
public:
    bool Init();
    void Run();
    void Shutdown();

    // One line to add a panel. Really one line.
    void AddPanel(std::unique_ptr<Panel> panel);

private:
    void DrawMenuBar();
    void DrawPanels();

    // The list of scenes in the File menu is DISCOVERED from assets/scenes/
    // rather than written down, so dropping a .json in there puts it in the
    // menu with no rebuild.
    void RefreshSceneList();
    void LoadScene(const std::string& virtualPath);
    void SaveScene(const std::string& virtualPath);   // empty = save where it came from
    void DrawSaveAsPopup();

    // Play hands the keyboard to the Game view. This lives here rather than in
    // the panel because at the moment Play is pressed the Game view is a
    // background tab, so its own Draw is not running. See GamePanel.h.
    void FocusGameViewIfRequested();

    // Called when the editor window regains focus - the user alt-tabbed away,
    // edited a script in their text editor, and came back. If anything in
    // any script under assets/ has changed, it is rebuilt and reloaded before
    // the next frame.
    // See ScriptBuild.h.
    void RebuildScriptsIfChanged();

    std::vector<std::unique_ptr<Panel>> m_panels;
    std::vector<std::string>            m_sceneList;

    // The two VIEWS. They are owned by m_panels like everything else; these
    // are non-owning pointers, because EditorApp has to drive them beyond
    // Draw() - both need RenderView() called after every panel has drawn, and
    // the Game view needs focus routed to it when Play is pressed. Every other
    // panel is reached only through the base class, which is exactly why only
    // these two are named here.
    class ScenePanel* m_scenePanel = nullptr;
    class GamePanel*  m_gamePanel  = nullptr;

    char m_saveAsPath[256] = {};
    bool m_openSaveAsPopup = false;
    char m_status[256]     = {};

    // True when the last script build failed. Shown in the menu bar, because a
    // failed build means the scripts that were running have just stopped and
    // that should not be something you have to go looking for.
    bool m_scriptBuildFailed = false;
};

} // namespace editor
