// =============================================================================
//  WEEK 2 - PROVIDED. Do not edit this file.
//
//  These cases exercise the seeded bugs. Some of them will fail loudly. Some
//  will PASS while the code underneath is still broken, because a test can
//  only observe what it looks at, and heap corruption is not observable from
//  inside the program that caused it.
// =============================================================================

#include <doctest/doctest.h>
#include <engine/core/ByteBuffer.h>
#include <cstring>

using namespace eng;

TEST_CASE("a fresh buffer has the requested size and is zeroed") {
    ByteBuffer b(16);
    CHECK(b.Size() == 16);
    for (usize i = 0; i < b.Size(); ++i) {
        CHECK(b.Data()[i] == 0);
    }
}

TEST_CASE("Fill sets every byte and does not touch anything else") {
    // The guard bytes on either side are how this case tries to notice an
    // overrun. Whether it succeeds depends on where the allocator happened to
    // put things, which is exactly why you cannot rely on it.
    ByteBuffer before(8);
    ByteBuffer target(8);
    ByteBuffer after(8);

    before.Fill(0xAA);
    after.Fill(0xAA);
    target.Fill(0x42);

    for (usize i = 0; i < target.Size(); ++i) {
        CHECK(target.Data()[i] == 0x42);
    }
    CHECK(before.Data()[0] == 0xAA);
    CHECK(after.Data()[0] == 0xAA);
}

TEST_CASE("Write copies the requested number of bytes") {
    ByteBuffer b(32);
    const char* message = "abcdefgh";

    REQUIRE(b.Write(4, message, 8));

    CHECK(b.Data()[3] == 0);                 // untouched before the offset
    CHECK(std::memcmp(b.Data() + 4, message, 8) == 0);
    CHECK(b.Data()[12] == 0);                // untouched after the range
}

TEST_CASE("Write refuses a range that would not fit") {
    ByteBuffer b(8);
    const char* message = "abcdefgh";
    CHECK_FALSE(b.Write(4, message, 8));
}

TEST_CASE("a copied buffer is independent of its source") {
    ByteBuffer original(8);
    original.Fill(0x11);

    ByteBuffer copy(original);
    copy.Fill(0x22);

    CHECK(original.Data()[0] == 0x11);   // must not have been changed
    CHECK(copy.Data()[0] == 0x22);
}

TEST_CASE("DescribeBuffer returns text that survives the call") {
    ByteBuffer b(64);
    const char* description = DescribeBuffer(b);

    // Calling something else in between is what turns a latent bug into a
    // visible one. Without these two lines the broken version often "works".
    ByteBuffer noise(128);
    noise.Fill(0xFF);

    CHECK(std::strstr(description, "64") != nullptr);
}

TEST_CASE("Release makes the buffer empty and is safe to double up on") {
    ByteBuffer b(16);
    b.Release();
    CHECK(b.Size() == 0);
    CHECK(b.Data() == nullptr);
    b.Release();   // must not crash
}
