#pragma once

// ============================================================================
//  Panel.h - the base class every editor window inherits from.
//
//  Adding a new panel is: write a class that inherits Panel, give it a title
//  and a Draw function, and add one line to EditorApp::Init. It then appears
//  in the View menu automatically, because that menu is generated by looping
//  over the list of panels rather than written out by hand.
//
//  ==========================================================================
//  IMMEDIATE MODE - the thing that is genuinely different here
//
//  In most interface toolkits you CREATE a button, it exists from then on, and
//  you attach a click handler to it. Dear ImGui does not work that way. You
//  CALL a function every single frame, and the button exists only for that
//  frame:
//
//      if (ImGui::Button("Reload")) { DoReload(); }
//
//  There is no button object and no handler. Button() draws a button and
//  returns true on the frame it was clicked.
//
//  Two consequences worth knowing before you write a panel:
//
//   * PANELS HOLD ALMOST NO STATE. The information lives in the engine and the
//     panel reads it fresh every frame, so it can never show you something out
//     of date. The exceptions in this editor are the Console's filters and the
//     current selection, and both of those are USER PREFERENCES rather than
//     information about the game - which is the test for whether a panel is
//     allowed to remember something.
//
//   * WIDGETS ARE IDENTIFIED BY THEIR LABEL. Two buttons both labelled
//     "Delete" in one window are the SAME widget as far as ImGui is concerned.
//     Give them different hidden ids with "##": "Delete##entity7". Anything
//     after ## is part of the identity and is not drawn.
//
//  ==========================================================================
//  Begin() AND End() ARE CALLED BY EditorApp, NOT BY Draw().
//
//  Decided once and applied to every panel, so that opening, closing, docking
//  and the little X button behave identically everywhere. Mixing the two
//  conventions produces mismatched Begin/End calls, which ImGui complains
//  about in a way that is worth meeting only once.
// ============================================================================

namespace editor {

class Panel {
public:
    virtual ~Panel() = default;

    // The window title, which ImGui also uses as the window's identity - so it
    // has to be unique across all panels.
    virtual const char* Title() const = 0;

    // Draws the CONTENTS of the panel. The window itself has already been
    // opened by the caller.
    virtual void Draw() = 0;

    // Called INSTEAD of Draw on a frame when the panel is not visible - closed,
    // collapsed, or sitting behind another tab.
    //
    // This exists because of a bug that is easy to write and hard to see. A
    // panel that works out "do I have keyboard focus?" during Draw keeps
    // whatever it last decided once it becomes a background tab, because Draw
    // stops being called at all. The Game view then reported that it still had
    // the keyboard while sitting behind the Scene tab, and every key went to a
    // game nobody could see.
    virtual void OnHidden() {}

    bool  IsOpen() const   { return m_open; }
    void  SetOpen(bool on) { m_open = on; }
    bool* OpenFlag()       { return &m_open; }

protected:
    bool m_open = true;
};

} // namespace editor
